apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/kubernetes-airflow-dbt/locations/us-central1/clusters/autopilot-cluster-1

