apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/kubernetes-airflow-dbt/locations/us-central1/clusters/autopilot-cluster-2

